import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { type ReactNode } from "react";
import { StyleSheet, Text, View } from "react-native";
import { riskColors, type MetricAssessment, type RiskLevel } from "@/lib/safety";

export function RiskPill({ level, label }: { level: RiskLevel; label?: string }) { const colors = riskColors[level]; return <View style={[styles.pill, { backgroundColor: colors.background, borderColor: colors.border }]}><Text style={[styles.pillText, { color: colors.text }]}>{label ?? colors.label}</Text></View>; }
export function ScreenTitle({ eyebrow, title, subtitle }: { eyebrow: string; title: string; subtitle?: string }) { return <View style={styles.titleBlock}><Text style={styles.eyebrow}>{eyebrow}</Text><Text style={styles.title}>{title}</Text>{subtitle ? <Text style={styles.subtitle}>{subtitle}</Text> : null}</View>; }
export function SignalIcon({ name, level = "normal" }: { name: React.ComponentProps<typeof MaterialIcons>["name"]; level?: RiskLevel }) { const colors = riskColors[level]; return <View style={[styles.signalIcon, { backgroundColor: colors.background }]}><MaterialIcons name={name} size={21} color={colors.text} /></View>; }
export function MetricCard({ assessment, icon }: { assessment: MetricAssessment; icon: React.ComponentProps<typeof MaterialIcons>["name"] }) { return <View style={styles.metricCard}><View style={styles.metricTopline}><SignalIcon name={icon} level={assessment.level} /><RiskPill level={assessment.level} /></View><Text style={styles.metricLabel}>{assessment.label}</Text><Text style={styles.metricValue}>{assessment.valueLabel}</Text><Text style={styles.metricStandard}>Standard: {assessment.standard.standard}</Text></View>; }
export function SectionHeading({ title, action }: { title: string; action?: ReactNode }) { return <View style={styles.sectionHeading}><Text style={styles.sectionTitle}>{title}</Text>{action}</View>; }
export function Notice({ level, icon, children }: { level: RiskLevel; icon: React.ComponentProps<typeof MaterialIcons>["name"]; children: ReactNode }) { const colors = riskColors[level]; return <View style={[styles.notice, { backgroundColor: colors.background, borderColor: colors.border }]}><MaterialIcons name={icon} size={21} color={colors.text} style={styles.noticeIcon} /><View style={styles.noticeContent}>{children}</View></View>; }
export const sharedStyles = StyleSheet.create({ scrollContent: { padding: 20, paddingBottom: 36, gap: 18 }, card: { backgroundColor: "#FFFFFF", borderRadius: 20, padding: 16, borderWidth: 1, borderColor: "#E7ECF1" }, fullButton: { minHeight: 50, borderRadius: 15, alignItems: "center", justifyContent: "center", paddingHorizontal: 16 }, buttonText: { color: "#FFFFFF", fontSize: 15, fontWeight: "800" }, outlineButton: { minHeight: 46, borderRadius: 14, alignItems: "center", justifyContent: "center", paddingHorizontal: 14, borderWidth: 1, borderColor: "#D7E1EA" }, outlineButtonText: { color: "#0B1F33", fontSize: 14, fontWeight: "800" } });
const styles = StyleSheet.create({ pill: { paddingHorizontal: 9, paddingVertical: 5, borderRadius: 99, borderWidth: 1 }, pillText: { fontSize: 11, lineHeight: 14, fontWeight: "800" }, titleBlock: { gap: 4 }, eyebrow: { color: "#0A8A7B", fontSize: 12, lineHeight: 16, fontWeight: "800", letterSpacing: 0.8, textTransform: "uppercase" }, title: { color: "#0B1F33", fontSize: 30, lineHeight: 37, fontWeight: "900", letterSpacing: -0.8 }, subtitle: { color: "#66758A", fontSize: 14, lineHeight: 20 }, signalIcon: { width: 39, height: 39, borderRadius: 13, justifyContent: "center", alignItems: "center" }, metricCard: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E7ECF1", borderRadius: 18, padding: 14, gap: 4, flex: 1 }, metricTopline: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 7 }, metricLabel: { color: "#53657A", fontSize: 12, lineHeight: 16, fontWeight: "700" }, metricValue: { color: "#0B1F33", fontSize: 21, lineHeight: 27, fontWeight: "900", letterSpacing: -0.45 }, metricStandard: { color: "#7B8798", fontSize: 10, lineHeight: 14 }, sectionHeading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, sectionTitle: { color: "#0B1F33", fontSize: 18, lineHeight: 24, fontWeight: "900", letterSpacing: -0.2 }, notice: { borderRadius: 16, padding: 14, borderWidth: 1, flexDirection: "row" }, noticeIcon: { marginRight: 10, marginTop: 1 }, noticeContent: { flex: 1, gap: 3 } });
