import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Link } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Notice, RiskPill, ScreenTitle, sharedStyles } from "@/components/safety-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useSafety } from "@/lib/safety-context";
const icons = { heartRateBpm: "favorite" as const, respiratoryRateBrpm: "air" as const, bodyTemperatureC: "device-thermostat" as const, ambientOxygenPercent: "air" as const, methanePercent: "local-fire-department" as const, carbonMonoxidePpm: "cloud" as const };
export default function ReadingsScreen() { const { telemetry, evaluation } = useSafety(); return <ScreenContainer><ScrollView contentContainerStyle={sharedStyles.scrollContent} showsVerticalScrollIndicator={false}><ScreenTitle eyebrow="Live telemetry" title="Sensor readings" subtitle={`Band ${telemetry.bandId} • ${telemetry.recordedAt}`} /><Notice level="normal" icon="verified-user"><Text style={styles.noticeTitle}>Reading / Standard / Status</Text><Text style={styles.noticeBody}>Every status is calculated against the visible source-linked standard. Physiological values are general adult resting references.</Text></Notice><View style={styles.tableCard}><View style={styles.tableHeader}><Text style={[styles.headerCell, styles.metricCol]}>SENSOR</Text><Text style={[styles.headerCell, styles.readingCol]}>READING</Text><Text style={[styles.headerCell, styles.standardCol]}>STANDARD</Text></View>{evaluation.assessments.map((item) => <View key={item.key} style={styles.tableRow}><View style={styles.metricCol}><View style={styles.rowLabel}><MaterialIcons name={icons[item.key]} size={17} color="#0A8A7B" /><Text style={styles.sensorName}>{item.label}</Text></View><RiskPill level={item.level} label={item.statusLabel} /></View><Text style={[styles.readingValue, styles.readingCol]}>{item.valueLabel}</Text><Text style={[styles.standardValue, styles.standardCol]}>{item.standard.standard}</Text></View>)}</View><Link href="/standards" asChild><Pressable style={({ pressed }) => [styles.standardButton, pressed && styles.pressed]}><View><Text style={styles.standardButtonTitle}>Check sources and scope</Text><Text style={styles.standardButtonBody}>See who set each standard and what it means.</Text></View><MaterialIcons name="arrow-forward" size={20} color="#087D70" /></Pressable></Link></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ noticeTitle: { color: "#087D70", fontSize: 14, fontWeight: "900" }, noticeBody: { color: "#236A63", fontSize: 12, lineHeight: 18 }, tableCard: { backgroundColor: "#FFFFFF", borderRadius: 20, overflow: "hidden", borderWidth: 1, borderColor: "#E7ECF1" }, tableHeader: { flexDirection: "row", backgroundColor: "#F4F7FA", paddingHorizontal: 14, paddingVertical: 12 }, headerCell: { color: "#66758A", fontSize: 10, lineHeight: 13, fontWeight: "900", letterSpacing: 0.55 }, tableRow: { flexDirection: "row", padding: 14, borderTopWidth: 1, borderTopColor: "#E7ECF1", alignItems: "center" }, metricCol: { flex: 1.24, gap: 8 }, readingCol: { flex: 0.85 }, standardCol: { flex: 1.18 }, rowLabel: { flexDirection: "row", alignItems: "center", gap: 6 }, sensorName: { color: "#0B1F33", fontSize: 13, lineHeight: 17, fontWeight: "800", flex: 1 }, readingValue: { color: "#173047", fontSize: 12, lineHeight: 17, fontWeight: "800", paddingRight: 6 }, standardValue: { color: "#66758A", fontSize: 11, lineHeight: 16 }, standardButton: { backgroundColor: "#EFFBF9", borderRadius: 17, padding: 15, flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderWidth: 1, borderColor: "#BCEBE4" }, standardButtonTitle: { color: "#087D70", fontSize: 14, fontWeight: "900", marginBottom: 3 }, standardButtonBody: { color: "#28756C", fontSize: 12, lineHeight: 17 }, pressed: { opacity: 0.74, transform: [{ scale: 0.98 }] } });
